// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MineDyrAPI.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MineDyrAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250428210042_AddCascadeDelete")]
    partial class AddCascadeDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MineDyrAPI.Entities.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Animals", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Toto",
                            OwnerId = 1,
                            Species = "Dog"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Whiskers",
                            OwnerId = 2,
                            Species = "Cat"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bella",
                            OwnerId = 2,
                            Species = "Dog"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Buster",
                            OwnerId = 1,
                            Species = "Cat"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bubba",
                            OwnerId = 1,
                            Species = "Dog"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bingo",
                            OwnerId = 2,
                            Species = "Cat"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Snowball",
                            OwnerId = 4,
                            Species = "Rabbit"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Max",
                            OwnerId = 5,
                            Species = "Dog"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Luna",
                            OwnerId = 3,
                            Species = "Cat"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Charlie",
                            OwnerId = 5,
                            Species = "Parrot"
                        });
                });

            modelBuilder.Entity("MineDyrAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Alice",
                            LastName = "Hansson"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Bob",
                            LastName = "Jackson"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Charlie",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "David",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Eve",
                            LastName = "White"
                        });
                });

            modelBuilder.Entity("MineDyrAPI.Entities.Animal", b =>
                {
                    b.HasOne("MineDyrAPI.Entities.User", "Owner")
                        .WithMany("Animals")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MineDyrAPI.Entities.User", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
